img_publisher:
    ros__parameters:
        camera_device: 0
        width: 320
        height: 240 
        frame_rate : 30

hsv_converter:
    ros__parameters:
        saturation_scale: 1.0
        value_scale: 1.0
        
cartoon_styler:
    ros__parameters:
        sigma_color: 20
        sigma_space: 9

edge_detect:
    ros__parameters:
        threshold1: 100
        threshold2: 200